apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config-map
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']
    - job_name: 'traefik'
      static_configs:
      - targets: ['traefik-metrics:9102']
    - job_name: 'blazor-demo'
      static_configs:
      - targets: ['blazor-demo:52325']