version: '3.8'

services:
  n8n:
    image: n8nio/n8n:next
    volumes:
      - ./data/n8n:/home/node/.n8n
    ports:
      - "5678:5678"
    networks:
      - n8n-net
    
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ./data/ollama:/root/.ollama
    networks:
      - n8n-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu] 

  mcp-fetch:
    build:
      context: ./res/mcp-proxy-uv
    command: ["--sse-port=8080", "--sse-host=0.0.0.0", "uvx", "mcp-server-fetch"]
    networks:
      - n8n-net
  
  mcp-filesystem:
    build:
      context: ./res/mcp-proxy-filesystem
    command: ["/data"]
    volumes:
      - ./data:/data
    networks:
      - n8n-net

networks:
  n8n-net: