apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraMounts:
    - hostPath: "./data" # obviously it does not matter whether the path is surrounded by double quotes or not
      containerPath: /data
  extraPortMappings:
  - containerPort: 80
    hostPort: 12080
    protocol: TCP