apiVersion: v1
kind: Pod
metadata:
  name: curl
  labels:
    app: curl
spec:
  containers:
    - name: curl-container
      image: curlimages/curl:latest
      command: ["sleep", "3600"] # Keeps the pod running