kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9102'
    spec:
      serviceAccountName: traefik-controller
      containers:
      - name: traefik
        image: traefik
        ports:
        - name: web
          containerPort: 80
        # - name: tcp
        #   containerPort: 8000
        - name: websecure
          containerPort: 443
        - name: metrics
          containerPort: 9102
        args:
        #- --api.insecure
        - --api.dashboard=true
        - --accesslog
        - --entrypoints.web.Address=:80
        - --entrypoints.websecure.address=:443
        - --entrypoints.metrics.address=:9102
        #- --entrypoints.tcpep.address=:8000
        - --providers.kubernetescrd    # custom resource definition
        - --providers.kubernetesingress
        - --certificatesresolvers.myresolver.acme.tlschallenge
        - --certificatesresolvers.myresolver.acme.email=mwinkler@gmx.ch
        - --certificatesresolvers.myresolver.acme.storage=acme.json
        - --metrics.prometheus=true
        - --metrics.prometheus.entryPoint=metrics
        resources:
          limits:
            memory: 128Mi
            cpu: 100m