apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: blazor-demo-ingress
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`blazor.mwinkler.ga`) || Host(`blazor.localhost`)
    kind: Rule
    services:
    - kind: TraefikService
      name: noop@internal
    middlewares:
    - name: https-redirect

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: blazor-demo-ingress-tls
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`blazor.mwinkler.ga`) || Host(`blazor.localhost`)
    kind: Rule
    services:
    - name: blazor-demo
      port: 80
  tls:
    certResolver: myresolver